// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// fill.cpp
SEXP fillDown(SEXP x);
extern "C" SEXP _tidyfast_fillDown(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(fillDown(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// fill.cpp
SEXP fillUp(SEXP x);
extern "C" SEXP _tidyfast_fillUp(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(fillUp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tidyfast_fillDown", (DL_FUNC) &_tidyfast_fillDown, 1},
    {"_tidyfast_fillUp",   (DL_FUNC) &_tidyfast_fillUp,   1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_tidyfast(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
